//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class heces
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public heces()
        {
            this.examenes = new HashSet<examenes>();
        }
    
        public int id_heces { get; set; }
        public Nullable<int> id_protozoarios_activos { get; set; }
        public Nullable<int> id_protozoarios_quistes { get; set; }
        public string color { get; set; }
        public string consistencia { get; set; }
        public string mucus { get; set; }
        public string hematies { get; set; }
        public string leucocitos { get; set; }
        public string macrofagos { get; set; }
        public string restos_alimenticios_macroscopicos { get; set; }
        public string trichuris_trichiura { get; set; }
        public string ascaris_lumbricoides { get; set; }
        public string uncinaria { get; set; }
        public string strongyloides_stercoralis { get; set; }
        public string entorobius_vermicularis { get; set; }
        public string taenias_sp { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examenes> examenes { get; set; }
        public virtual protozoarios_activos protozoarios_activos { get; set; }
        public virtual protozoarios_quistes protozoarios_quistes { get; set; }
    }
}
