//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class hemograma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hemograma()
        {
            this.examenes = new HashSet<examenes>();
        }
    
        public int id_hemograma { get; set; }
        public string globulos_rojos { get; set; }
        public string hemoglobina { get; set; }
        public string hematocrito { get; set; }
        public string vgm { get; set; }
        public string hcm { get; set; }
        public string chcm { get; set; }
        public string leucocitos { get; set; }
        public string neutrofilos_segmentados { get; set; }
        public string neutrofilos_en_banda { get; set; }
        public string linfocitos { get; set; }
        public string eosinofilo { get; set; }
        public string basofilo { get; set; }
        public string monocitos { get; set; }
        public string plaquetas { get; set; }
        public string macroplaquetas { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examenes> examenes { get; set; }
    }
}
