//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laboratorio_pEntities : DbContext
    {
        public laboratorio_pEntities()
            : base("name=laboratorio_pEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<campaña> campaña { get; set; }
        public virtual DbSet<examenes> examenes { get; set; }
        public virtual DbSet<heces> heces { get; set; }
        public virtual DbSet<hemograma> hemograma { get; set; }
        public virtual DbSet<orina> orina { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<protozoarios_activos> protozoarios_activos { get; set; }
        public virtual DbSet<protozoarios_quistes> protozoarios_quistes { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
