//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orina()
        {
            this.examenes = new HashSet<examenes>();
        }
    
        public int id_orina { get; set; }
        public string color { get; set; }
        public string aspecto { get; set; }
        public string densidad { get; set; }
        public string ph { get; set; }
        public string proteinas { get; set; }
        public string glucosa { get; set; }
        public string sangre_oculta { get; set; }
        public string cuerpos_cetonicos { get; set; }
        public string urobilinogeno { get; set; }
        public string bilirrubina { get; set; }
        public string nitritos { get; set; }
        public string hemoglobina { get; set; }
        public string esteriasa_leucocitaria { get; set; }
        public string cilindros_granulosos { get; set; }
        public string leucocitarios { get; set; }
        public string hematicos { get; set; }
        public string hialinos { get; set; }
        public string hematies { get; set; }
        public string leucocitos { get; set; }
        public string celulas_epiteliales { get; set; }
        public string cristales { get; set; }
        public string parasitos { get; set; }
        public string observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examenes> examenes { get; set; }
    }
}
