//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class protozoarios_activos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public protozoarios_activos()
        {
            this.heces = new HashSet<heces>();
        }
    
        public int id_protozoarios_activos { get; set; }
        public string entamoeba_histolitica { get; set; }
        public string entamoeba_coli { get; set; }
        public string endolimax_nana { get; set; }
        public string guiardia_lamblia { get; set; }
        public string trichomonas_hominis { get; set; }
        public string chilomastrix_mesnili { get; set; }
        public string blostocistis_hominis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<heces> heces { get; set; }
    }
}
